@Todo_HostAddress = http://localhost:5137

GET {{Todo_HostAddress}}/api/TodoItems
Accept: application/json

###

POST {{Todo_HostAddress}}/api/TodoItems
Accept: application/json
Content-Type: application/json

{
  "name": "string",
  "isComplete": true
}
